# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD FacebookClone

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      NODE_ENV: production
      DEPLOYMENT_DIR: /home/ec2-user/facebook-clone-app

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test || true
    
    - name: Setup environment
      run: |
        cp .env.production .env
        # Replace placeholder values with GitHub secrets
        sed -i "s|\$JWT_SECRET|${{ secrets.JWT_SECRET }}|g" .env
        sed -i "s|\$EMAIL_USER|${{ secrets.EMAIL_USER }}|g" .env
        sed -i "s|\$EMAIL_PASSWORD|${{ secrets.EMAIL_PASSWORD }}|g" .env
        sed -i "s|\$FIREBASE_STORAGE_BUCKET|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g" .env
        sed -i "s|\$AWS_BUCKET_ACESS_KEY|${{ secrets.AWS_BUCKET_ACESS_KEY }}|g" .env
        sed -i "s|\$AWS_BUCKET_SECRET_KEY|${{ secrets.AWS_BUCKET_SECRET_KEY }}|g" .env
        sed -i "s|\$AWS_KEY_GROUP|${{ secrets.AWS_KEY_GROUP }}|g" .env
        sed -i "s|\$AWS_PRIVATE_KEY|${{ secrets.AWS_PRIVATE_KEY }}|g" .env
        
        
    - name: Prepare deployment package
      run: |
        # Create deployment directory if it doesn't exist
        mkdir -p ${{ env.DEPLOYMENT_DIR }}
        
        # Create or update deployment package with only necessary files
        mkdir -p deployment-package
        
        # Copy dist folder (compiled code)
        cp -r dist deployment-package/
        
        # Copy .env file
        cp .env deployment-package/
        
        # Copy package.json and package-lock.json
        cp package.json package-lock.json deployment-package/
        
        # Copy database initialization script
        mkdir -p deployment-package/dist/scripts
        cp -r dist/scripts/db-init.js deployment-package/dist/scripts/
        
    - name: Deploy to EC2
      run: |
        # Stop the existing PM2 process if it exists
        pm2 stop facebook-clone || true
        pm2 delete facebook-clone || true
        
        # Backup the current version if exists
        if [ -d "${{ env.DEPLOYMENT_DIR }}-backup" ]; then
          rm -rf ${{ env.DEPLOYMENT_DIR }}-backup
        fi
        
        if [ -d "${{ env.DEPLOYMENT_DIR }}" ]; then
          mv ${{ env.DEPLOYMENT_DIR }} ${{ env.DEPLOYMENT_DIR }}-backup
        fi
        
        # Copy deployment package to deployment directory
        cp -r deployment-package ${{ env.DEPLOYMENT_DIR }}
        
        # Install production dependencies only
        cd ${{ env.DEPLOYMENT_DIR }}
        npm install --production
        
    - name: Start Docker containers for database services
      run: |
        # Update docker-compose environment
        sed -i "s|MONGO_INITDB_ROOT_USERNAME=admin|MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGODB_USERNAME }}|g" docker-compose.yml
        sed -i "s|MONGO_INITDB_ROOT_PASSWORD=password|MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGODB_PASSWORD }}|g" docker-compose.yml
        sed -i "s|RABBITMQ_DEFAULT_USER=admin|RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_USERNAME }}|g" docker-compose.yml
        sed -i "s|RABBITMQ_DEFAULT_PASS=password|RABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_PASSWORD }}|g" docker-compose.yml
        
        # Copy docker-compose file to deployment directory
        cp docker-compose.yml ${{ env.DEPLOYMENT_DIR }}/
        
        # Stop and remove existing containers
        cd ${{ env.DEPLOYMENT_DIR }}
        docker-compose down
        
        # Start the database services
        docker-compose up -d mongodb redis rabbitmq
        
        # Wait for databases to be ready
        echo "Waiting for MongoDB to be ready..."
        sleep 10
        echo "Waiting for Redis to be ready..."
        sleep 5
        echo "Waiting for RabbitMQ to be ready..."
        sleep 10
        
        # Check database connections
        docker ps
    
    - name: Database migration and seed (if needed)
      run: |
        # Run migrations or initialize database if needed
        echo "Initializing databases if needed"
        cd ${{ env.DEPLOYMENT_DIR }}
        node dist/scripts/db-init.js || true
    
    - name: Start application
      run: |
        cd ${{ env.DEPLOYMENT_DIR }}
        # Start the application with PM2
        pm2 start npm --name "facebook-clone" -- start
        pm2 save
    
    - name: Monitor deployment
      run: |
        echo "Application deployed successfully to ${{ env.DEPLOYMENT_DIR }}"
        pm2 status
        
    - name: Cleanup
      run: |
        # Remove deployment package
        rm -rf deployment-package
